<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Login Page</title>
    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!-- Font-->
    <link rel="stylesheet" type="text/css" href="css/opensans-font.css">
    <link rel="stylesheet" type="text/css" href="fonts/material-design-iconic-font/css/material-design-iconic-font.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Main Style Css -->
    <link rel="stylesheet" href="css/style.css" />
</head>

<body>
<form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="POST">
    <div class="page-content">
        <div class="form-v1-content">
            <div class="wizard-form">
            <div class="form-register">
                    <div id="form-total">
                        <!-- SECTION 1 -->
                        <h2>
			            	<span class="step-text">Peronal Infomation</span>
			            </h2>
                        <section>
                            <div class="inner">
                                <div class="wizard-header">
                                    <h3 class="heading">Login</h3>
                                    <p>Please enter your infomation and proceed to the next step so you can connect and live new experience with food ordering. </p>
                                </div>
                                <div class="form-row">                          
                                </div>
                                <div class="form-row">
                                    <div class="form-holder form-holder-2">
                                        <fieldset>
                                            <legend>Your Email</legend>
                                            <input type="email" name="email" id="email" class="form-control" pattern="[^@]+@[^@]+.[a-zA-Z]{2,6}" placeholder="example@email.com" required>
                                            <span class="text-danger"><?php if (isset($email_error)) echo $email_error; ?></span>
                                        </fieldset>
                                    </div>
                                </div>
                                <div class="form-row">
                                <div class="form-holder form-holder-2">
                                        <fieldset>
                                            <legend>Your Password</legend>
                                            <input type="password" name="pwd" id="pwd" class="form-control" placeholder="Password" required>
                                            <span class="text-danger"><?php if (isset($pwd_error)) echo $pwd_error; ?></span>
                                        </fieldset>
                                    </div>
                                    <button type="submit" class="btn btn-primary btn-lg btn-block" name="login">Login</button>
                                    </div>
                                    <a href="signup.php">You dont Have an account?</a>
                                    <?php  if(!empty($_GET['msg']))
                                                    {echo $_GET['msg'];};?>
                            </div>
                        </section>
                    </div>
            </div>
        </div>
    </div>
</div>
</form>

    <script src="js/jquery-3.3.1.min.js"></script>
    <script src="js/jquery.steps.js"></script>
    <script src="js/main.js"></script>
</body>
</html>