<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>form-v1 by Colorlib</title>
    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!-- Font-->
    <link rel="stylesheet" type="text/css" href="css/opensans-font.css">
    <link rel="stylesheet" type="text/css" href="fonts/material-design-iconic-font/css/material-design-iconic-font.min.css">
    <!-- Main Style Css -->
    <link rel="stylesheet" href="css/style.css" />
</head>

<body>
    <div class="page-content">
        <div class="form-v1-content">
            <div class="wizard-form">
                <form class="form-register" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post">
                    <div id="form-total">
                        <!-- SECTION 1 -->
                        <h2>
			            	<p class="step-icon"><span>01</span></p>
			            	<span class="step-text">Peronal Infomation</span>
			            </h2>
                        <section>
                            <div class="inner">
                                <div class="wizard-header">
                                    <h3 class="heading">Peronal Infomation</h3>
                                    <p>Please enter your infomation and proceed to the next step so we can build your accounts. </p>
                                </div>
                                <div class="form-row">
                                <?php if (isset($auth_error)): ?>
                                    <div class="form-holder">
                                        <fieldset>
                                            <legend>First Name</legend>
                                            <input type="text" class="form-control" id="firstname" name="firstname" placeholder="First Name" required>
                                            <span class="text-danger"><?php if (isset($fname_error)) echo $fname_error; ?></span>
                                        </fieldset>
                                    </div>
                                    <div class="form-holder">
                                        <fieldset>
                                            <legend>Last Name</legend>
                                            <input type="text" class="form-control" id="lastname" name="lastname" placeholder="Last Name" required>
                                            <span class="text-danger"><?php if (isset($lname_error)) echo $lname_error; ?></span>
                                        </fieldset>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-holder form-holder-2">
                                        <fieldset>
                                            <legend>Your Email</legend>
                                            <input type="email" name="email" id="email" class="form-control" pattern="[^@]+@[^@]+.[a-zA-Z]{2,6}" placeholder="example@email.com" required>
                                            <span class="text-danger"><?php if (isset($email_error)) echo $email_error; ?></span>
                                        </fieldset>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-holder">
                                        <fieldset>
                                            <legend>Your Password</legend>
                                            <input type="password" name="password" id="password" class="form-control" placeholder="Password" required>
                                            <span class="text-danger"><?php if (isset($password_error)) echo $password_error; ?></span>
                                        </fieldset>
                                    </div>
                                    <div class="form-holder">
                                        <fieldset>
                                            <legend>Confirm Password</legend>
                                            <input type="password" name="cpassword" id="cpassword" class="form-control" placeholder="Confirm Password" required>
                                            <span class="text-danger"><?php if (isset($cpassword_error)) echo $cpassword_error; ?></span>
                                        </fieldset>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-holder form-holder-2">
                                        <fieldset>
                                            <legend>Phone Number</legend>
                                            <input type="text" class="form-control" id="phone" name="phone" placeholder="55 555 555" pattern="[0-9]{12}" required>
                                        </fieldset>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-holder form-holder-2">
                                        <fieldset>
                                            <legend>Adress</legend>
                                            <input type="text" class="form-control" id="adress" name="adress" placeholder="Rue Avenu, Tunis" required>
                                        </fieldset>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-holder form-holder-2">
                                        <fieldset>
                                            <legend>Choice a picture</legend>
                                            <input type="file" name="pic" accept="image/*" value="" required>
                                        </fieldset>
                                    </div>
                                </div>

                            </div>
                        </section>
                        <!-- SECTION 2 -->
                        <h2>
			            	<p class="step-icon"><span>02</span></p>
			            	<span class="step-text">Connect Bank Account</span>
			            </h2>
                        <section>
                            <div class="inner">
                                <div class="wizard-header">
                                    <h3 class="heading">Connect Bank Account</h3>
                                    <p>Please enter your infomation and proceed to the next step so we can build your accounts.</p>
                                </div>
                                <div class="form-row">
                                    <div class="form-holder">
                                        <fieldset>
                                            <legend>Cart Number</legend>
                                            <input type="text" class="form-control" id="cnumb" name="cnumb" placeholder="16 Digits" pattern="[0-9]{16}" required>
                                        </fieldset>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-holder">
                                        <fieldset>
                                            <legend>Expiration date</legend>
                                            <input type="date" class="form-control" id="date" name="date" placeholder="16 Digits" min="2019-12-10" required>
                                        </fieldset>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-holder">
                                        <fieldset>
                                            <legend>CCV</legend>
                                            <input type="text" class="form-control" id="ccv" name="ccv" placeholder="3 Digits" pattern="[0-9]{3}" required>
                                        </fieldset>
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="js/jquery-3.3.1.min.js"></script>
    <script src="js/jquery.steps.js"></script>
    <script src="js/main.js"></script>
</body>
<!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>